baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My website'
theme = 'cactus'

[taxonomies]
  tag = "tags"
  category = "categories"

[params]

  colortheme = "dark" # dark, light, white, or classic


  description = "Hompage text defined in config.toml"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "python reference"
url = "/py_ref"

weight = 2